# Use this file for generating a new image of the application

FROM openjdk:17

WORKDIR /app

COPY .mvn .mvn/
COPY mvnw pom.xml ./

RUN ./mvnw dependency:go-offline

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]
EXPOSE 8080